/**
 * The Fort Jiu-Jitsu - Stripe Product & Price IDs
 *
 * This file contains all Stripe product and price IDs for the gym.
 * These IDs are generated by running: npx ts-node scripts/setup-stripe-products.ts
 *
 * After running the setup script, replace the placeholder IDs below
 * with the actual IDs from your Stripe account.
 */

export interface StripeProduct {
  productId: string;
  monthlyPriceId?: string;
  annualPriceId?: string;
  oneTimePriceId?: string;
}

export const STRIPE_PRODUCTS: Record<string, StripeProduct> = {
  KIDS_BJJ: {
    productId: 'prod_TZsDC211IgXUm4',
    monthlyPriceId: 'price_1SciTWASerE5d23FJzvW2zfd', // $75/month
    annualPriceId: 'price_1SciTWASerE5d23FsJCBpnzQ', // $750/year (save $150)
  },
  ADULT_BJJ: {
    productId: 'prod_TZsDsDCuozLAlI',
    monthlyPriceId: 'price_1SciTXASerE5d23FHR2D1yiJ', // $100/month
    annualPriceId: 'price_1SciTYASerE5d23FWnOseDhi', // $1000/year (save $200)
  },
  FAMILY_PLAN: {
    productId: 'prod_TZsEek5X6N7h7E',
    monthlyPriceId: 'price_1SciTYASerE5d23FRqhclOuM', // $150/month
  },
  DROP_IN: {
    productId: 'prod_TZsEoSTBkNwcpf',
    oneTimePriceId: 'price_1SciTZASerE5d23FpjQ8ozhJ', // $20 one-time
  },
};

export const STRIPE_COUPONS = {
  FAMILY_DISCOUNT_25: 'FAMILY_DISCOUNT_25', // 25% off for family plans
  FIRST_WEEK_FREE: 'FIRST_WEEK_FREE', // 1 week free trial
  GRAND_OPENING_50: 'GRAND_OPENING_50', // 50% off first month
};

// Helper function to get price ID by membership type and interval
export function getPriceId(
  membershipType: 'kids-bjj' | 'adult-bjj' | 'family' | 'drop-in',
  interval: 'monthly' | 'annual' | 'one-time' = 'monthly'
): string {
  switch (membershipType) {
    case 'kids-bjj':
      return interval === 'annual'
        ? STRIPE_PRODUCTS.KIDS_BJJ.annualPriceId!
        : STRIPE_PRODUCTS.KIDS_BJJ.monthlyPriceId!;

    case 'adult-bjj':
      return interval === 'annual'
        ? STRIPE_PRODUCTS.ADULT_BJJ.annualPriceId!
        : STRIPE_PRODUCTS.ADULT_BJJ.monthlyPriceId!;

    case 'family':
      return STRIPE_PRODUCTS.FAMILY_PLAN.monthlyPriceId!;

    case 'drop-in':
      return STRIPE_PRODUCTS.DROP_IN.oneTimePriceId!;

    default:
      throw new Error(`Unknown membership type: ${membershipType}`);
  }
}

// Helper function to get product ID by membership type
export function getProductId(
  membershipType: 'kids-bjj' | 'adult-bjj' | 'family' | 'drop-in'
): string {
  switch (membershipType) {
    case 'kids-bjj':
      return STRIPE_PRODUCTS.KIDS_BJJ.productId;
    case 'adult-bjj':
      return STRIPE_PRODUCTS.ADULT_BJJ.productId;
    case 'family':
      return STRIPE_PRODUCTS.FAMILY_PLAN.productId;
    case 'drop-in':
      return STRIPE_PRODUCTS.DROP_IN.productId;
    default:
      throw new Error(`Unknown membership type: ${membershipType}`);
  }
}

// Pricing display helpers
export const PRICING_DISPLAY = {
  KIDS_BJJ: {
    monthly: {
      amount: 75,
      display: '$75/month',
      description: 'Ages 5-17 • 2x/week + morning rolls',
    },
    annual: {
      amount: 750,
      display: '$750/year',
      description: 'Save $150 (2 months free)',
    },
  },
  ADULT_BJJ: {
    monthly: {
      amount: 100,
      display: '$100/month',
      description: 'Ages 18+ • 2x/week + morning rolls',
      badge: 'Most Popular',
    },
    annual: {
      amount: 1000,
      display: '$1000/year',
      description: 'Save $200 (2 months free)',
    },
  },
  FAMILY_PLAN: {
    monthly: {
      amount: 150,
      display: '$150/month',
      description: '2+ family members • 25% savings',
    },
  },
  DROP_IN: {
    oneTime: {
      amount: 20,
      display: '$20',
      description: 'Single class • No commitment',
    },
  },
};

// Trial configuration
export const TRIAL_PERIOD_DAYS = 7; // 1 week free trial

// Determine if a member qualifies for family discount
export function qualifiesForFamilyDiscount(familyMemberCount: number): boolean {
  return familyMemberCount >= 2;
}

// Calculate family savings
export function calculateFamilySavings(
  adultCount: number,
  kidsCount: number
): {
  individualCost: number;
  familyCost: number;
  savings: number;
  savingsPercent: number;
} {
  const individualCost = adultCount * 100 + kidsCount * 75;
  const familyCost = 150;
  const savings = individualCost - familyCost;
  const savingsPercent = Math.round((savings / individualCost) * 100);

  return {
    individualCost,
    familyCost,
    savings,
    savingsPercent,
  };
}
